# Generated by Django 4.1.5 on 2023-01-23 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_question_penalty_alter_question_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionaire',
            name='PIN',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionaire',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
